### ISSUE TITLE
EditorConfig file not visible in file list of Netbeans 8.1

### ISSUE THREAD

**Issue by llaville** [welovecoding/editorconfig-netbeans#96]
Hello,

I've just tried today your plugin in version 0.1.0 with Netbeans 8.1 on Windows platform 32 bits (Vista).

I was surprised to not see it in projects list on left panel (see screenshot) while we can see in on your project page.  Did I miss something ?

Thanks in advance for any support 
Laurent
![editorconfig_netbeans_81](https://cloud.githubusercontent.com/assets/364342/13897797/5d829fba-edbe-11e5-8f38-e7ea937501a4.png)

**Comment by phantom-d** [comment]
Uncheck checkbox. Look on screenshot.
![screenshot](https://cloud.githubusercontent.com/assets/5058892/14095091/4674f8be-f565-11e5-8e18-f027a6f9b375.jpg)

**Comment by llaville** [comment]
@phantom-d Thanks for the tip / but finally it does not come from the checkbox. But rather to the ignore File Pattern I have 

```
^(CVS|SCCS|vssver.?\.scc|#.*#|%.*%|_svn)$|~$|^\.(?!(htaccess|git.+|hgignore)$).*$
```

**Comment by hhallou** [comment]
Hi,
Am working with netbeans 8.1 and I've just installed this plugin. When i activate the plugin, none of my projects will open.
Here's what I get 
`INFO [com.welovecoding.nbeditorconfig.listener.ProjectHookLookup]: Setup hooks for: EmploiPublic
SEVERE [org.openide.util.RequestProcessor]: Error in RequestProcessor org.netbeans.modules.project.ui.ProjectChooserAccessory$1
java.lang.NoClassDefFoundError: com/welovecoding/nbeditorconfig/listener/ProjectOpenCloseListener
	at com.welovecoding.nbeditorconfig.listener.ProjectHookLookup.createAdditionalLookup(ProjectHookLookup.java:53)
	at org.netbeans.spi.project.support.DelegatingLookupImpl.doDelegate(DelegatingLookupImpl.java:139)
	at org.netbeans.spi.project.support.DelegatingLookupImpl.<init>(DelegatingLookupImpl.java:91)
	at org.netbeans.spi.project.support.LookupProviderSupport.createCompositeLookup(LookupProviderSupport.java:95)
	at org.netbeans.modules.php.project.PhpProject.createLookup(PhpProject.java:778)
	at org.netbeans.modules.php.project.PhpProject.<init>(PhpProject.java:304)
Caused: java.lang.reflect.InvocationTargetException
	at sun.reflect.GeneratedConstructorAccessor13.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at org.netbeans.modules.project.ant.AntBasedGenericType.createProject(AntBasedGenericType.java:131)
Caused: java.lang.IllegalArgumentException
	at org.netbeans.modules.project.ant.AntBasedGenericType.createProject(AntBasedGenericType.java:140)
	at org.netbeans.modules.project.ant.AntBasedProjectFactorySingleton.loadProject(AntBasedProjectFactorySingleton.java:264)
	at org.netbeans.modules.projectapi.nb.NbProjectManager.createProject(NbProjectManager.java:401)
	at org.netbeans.modules.projectapi.nb.NbProjectManager.access$300(NbProjectManager.java:94)
	at org.netbeans.modules.projectapi.nb.NbProjectManager$2.run(NbProjectManager.java:314)
	at org.netbeans.modules.projectapi.nb.NbProjectManager$2.run(NbProjectManager.java:243)
	at org.netbeans.modules.openide.util.DefaultMutexImplementation.readAccess(DefaultMutexImplementation.java:252)
	at org.openide.util.Mutex.readAccess(Mutex.java:250)
	at org.netbeans.modules.projectapi.nb.NbProjectManager.findProject(NbProjectManager.java:243)
	at org.netbeans.api.project.ProjectManager.findProject(ProjectManager.java:167)
	at org.netbeans.modules.project.ui.OpenProjectList.fileToProject(OpenProjectList.java:1234)
	at org.netbeans.modules.project.ui.ProjectChooserAccessory.getProject(ProjectChooserAccessory.java:352)
	at org.netbeans.modules.project.ui.ProjectChooserAccessory.access$000(ProjectChooserAccessory.java:89)
	at org.netbeans.modules.project.ui.ProjectChooserAccessory$1.run(ProjectChooserAccessory.java:241)
	at org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:1443)
	at org.netbeans.modules.openide.util.GlobalLookup.execute(GlobalLookup.java:68)
	at org.openide.util.lookup.Lookups.executeWith(Lookups.java:303)
[catch] at org.openide.util.RequestProcessor$Processor.run(RequestProcessor.java:2058)
INFO [com.welovecoding.nbeditorconfig.listener.ProjectHookLookup]: Setup hooks for: EmploiMasterLib
SEVERE [org.openide.util.RequestProcessor]: Error in RequestProcessor org.netbeans.modules.project.ui.ProjectChooserAccessory$1
java.lang.NoClassDefFoundError: com/welovecoding/nbeditorconfig/listener/ProjectOpenCloseListener
	at com.welovecoding.nbeditorconfig.listener.ProjectHookLookup.createAdditionalLookup(ProjectHookLookup.java:53)
	at org.netbeans.spi.project.support.DelegatingLookupImpl.doDelegate(DelegatingLookupImpl.java:139)
	at org.netbeans.spi.project.support.DelegatingLookupImpl.<init>(DelegatingLookupImpl.java:91)
	at org.netbeans.spi.project.support.LookupProviderSupport.createCompositeLookup(LookupProviderSupport.java:95)
	at org.netbeans.modules.php.project.PhpProject.createLookup(PhpProject.java:778)
	at org.netbeans.modules.php.project.PhpProject.<init>(PhpProject.java:304)
Caused: java.lang.reflect.InvocationTargetException
	at sun.reflect.GeneratedConstructorAccessor13.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at org.netbeans.modules.project.ant.AntBasedGenericType.createProject(AntBasedGenericType.java:131)
Caused: java.lang.IllegalArgumentException
	at org.netbeans.modules.project.ant.AntBasedGenericType.createProject(AntBasedGenericType.java:140)
	at org.netbeans.modules.project.ant.AntBasedProjectFactorySingleton.loadProject(AntBasedProjectFactorySingleton.java:264)
	at org.netbeans.modules.projectapi.nb.NbProjectManager.createProject(NbProjectManager.java:401)
	at org.netbeans.modules.projectapi.nb.NbProjectManager.access$300(NbProjectManager.java:94)
	at org.netbeans.modules.projectapi.nb.NbProjectManager$2.run(NbProjectManager.java:314)
	at org.netbeans.modules.projectapi.nb.NbProjectManager$2.run(NbProjectManager.java:243)
	at org.netbeans.modules.openide.util.DefaultMutexImplementation.readAccess(DefaultMutexImplementation.java:252)
	at org.openide.util.Mutex.readAccess(Mutex.java:250)
	at org.netbeans.modules.projectapi.nb.NbProjectManager.findProject(NbProjectManager.java:243)
	at org.netbeans.api.project.ProjectManager.findProject(ProjectManager.java:167)
	at org.netbeans.modules.project.ui.OpenProjectList.fileToProject(OpenProjectList.java:1234)
	at org.netbeans.modules.project.ui.ProjectChooserAccessory.getProject(ProjectChooserAccessory.java:352)
	at org.netbeans.modules.project.ui.ProjectChooserAccessory.access$000(ProjectChooserAccessory.java:89)
	at org.netbeans.modules.project.ui.ProjectChooserAccessory$1.run(ProjectChooserAccessory.java:241)
	at org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:1443)
	at org.netbeans.modules.openide.util.GlobalLookup.execute(GlobalLookup.java:68)
	at org.openide.util.lookup.Lookups.executeWith(Lookups.java:303)
[catch] at org.openide.util.RequestProcessor$Processor.run(RequestProcessor.java:2058)
`

**Comment by ZaLiTHkA** [comment]
@hhallou, it would be better for you to open a [new issue report](https://github.com/welovecoding/editorconfig-netbeans/issues/new) for this one. This report is about a different issue that was already solved.. Also don't forget to include some more information, like your IDE JDK version, operating system, etc. :)
